apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: free-ebay
  labels:
    app: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: free-ebay/email-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: common-config
            - secretRef:
                name: email-service-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"