# Run shared infra first:  docker compose -f ../docker-compose.infra.yml up -d
name: search-service-deps

networks:
  free-ebay-local:
    external: true

services:
  # search-service:
  #   build: .
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     Elasticsearch__Url: "http://elasticsearch:9200"
  #     Elasticsearch__IndexName: "products"
  #     AiSearch__Enabled: "true"
  #     AiSearch__GrpcUrl: "http://ai-search-service:50051"
  #     Kestrel__EndpointDefaults__Protocols: Http2
  #     ASPNETCORE_URLS: "http://+:8080"
  #     Otel__Endpoint: "http://jaeger:4317"
  #   ports:
  #     - "8088:8080"
  #   networks:
  #     - free-ebay-local
