export const CREATE_PRODUCT_USE_CASE = Symbol('CREATE_PRODUCT_USE_CASE');
export const DELETE_PRODUCT_USE_CASE = Symbol('DELETE_PRODUCT_USE_CASE');
export const FIND_PRODUCT_USE_CASE = Symbol('FIND_PRODUCT_USE_CASE');
export const FIND_PRODUCTS_USE_CASE = Symbol('FIND_PRODUCTS_USE_CASE');
export const MARK_AS_AVAILABLE_USE_CASE = Symbol('MARK_AS_AVAILABLE_USE_CASE');
export const MARK_AS_OUT_OF_STOCK_USE_CASE = Symbol(
  'MARK_AS_OUT_OF_STOCK_USE_CASE',
);
