# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"I\n\x12\x45mbedStreamRequest\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\"Q\n\x13\x45mbedStreamResponse\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x12\n\ndimensions\x18\x03 \x01(\x05\x32\x64\n\x10\x45mbeddingService\x12P\n\x0b\x45mbedStream\x12\x1d.embedding.EmbedStreamRequest\x1a\x1e.embedding.EmbedStreamResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDSTREAMREQUEST']._serialized_start=30
  _globals['_EMBEDSTREAMREQUEST']._serialized_end=103
  _globals['_EMBEDSTREAMRESPONSE']._serialized_start=105
  _globals['_EMBEDSTREAMRESPONSE']._serialized_end=186
  _globals['_EMBEDDINGSERVICE']._serialized_start=188
  _globals['_EMBEDDINGSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
