apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: free-ebay
data:
  init.sql: |
    -- Create types
    CREATE TYPE IF NOT EXISTS "public"."products_status_enum" AS ENUM('Available', 'OutOfStock', 'Discontinued', 'Pending');
    CREATE TYPE IF NOT EXISTS "public"."shipments_shipmentstatus_enum" AS ENUM('Pending', 'Shipped', 'Delivered', 'Cancelled');
    CREATE TYPE IF NOT EXISTS "public"."payments_paymentstatus_enum" AS ENUM('Pending', 'Completed', 'Paid', 'Failed', 'Refunded', 'Cancelled');
    CREATE TYPE IF NOT EXISTS "public"."payments_paymentmethod_enum" AS ENUM('creditCard', 'Paypal', 'BankTransfer', 'CashOnDelivery', 'ApplePay', 'GooglePay', 'Cryptocurrency');
    CREATE TYPE IF NOT EXISTS "public"."orders_status_enum" AS ENUM('Pending', 'Shipped', 'Cancelled');

    -- Create tables if they don't exist
    CREATE TABLE IF NOT EXISTS "categories" (
      "id" character varying NOT NULL, 
      "name" character varying NOT NULL, 
      "description" character varying, 
      "parentCategoryId" character varying, 
      CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), 
      CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "products" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "name" character varying NOT NULL, 
      "description" character varying NOT NULL, 
      "price" jsonb NOT NULL, 
      "status" "public"."products_status_enum" NOT NULL DEFAULT 'Available', 
      "category_id" character varying, 
      CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "shipments" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "shipmentStatus" "public"."shipments_shipmentstatus_enum" NOT NULL DEFAULT 'Pending', 
      "trackingNumber" character varying(255) NOT NULL, 
      "shippedAt" TIMESTAMP, 
      "estimatedArrival" TIMESTAMP, 
      "order_id" character varying,
      "address" character varying(80) NOT NULL,
      CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "payments" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "paymentStatus" "public"."payments_paymentstatus_enum" NOT NULL DEFAULT 'Pending', 
      "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL, 
      "amount" jsonb NOT NULL, 
      "paymentDate" TIMESTAMP NOT NULL DEFAULT now(), 
      "order_id" character varying, 
      "user_id" character varying, 
      CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "orders" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "totalPrice" jsonb NOT NULL, 
      "status" "public"."orders_status_enum" NOT NULL DEFAULT 'Shipped', 
      "user_id" character varying, 
      "shipment_id" character varying, 
      CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "users" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "email" character varying NOT NULL, 
      "password" character varying NOT NULL, 
      CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "cart_items" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "cartId" character varying NOT NULL, 
      "productId" character varying NOT NULL, 
      "quantity" integer NOT NULL, 
      "price" jsonb NOT NULL, 
      CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "carts" (
      "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
      "id" character varying NOT NULL, 
      "user_id" character varying, 
      CONSTRAINT "REL_69828a178f152f157dcf2f70a4" UNIQUE ("user_id"), 
      CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id")
    );

    CREATE TABLE IF NOT EXISTS "order_items" (
      "id" character varying NOT NULL, 
      "orderId" character varying NOT NULL, 
      "productId" character varying NOT NULL, 
      "quantity" integer NOT NULL, 
      "price" jsonb NOT NULL, 
      CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id")
    );

    -- Create migrations table if it doesn't exist
    CREATE TABLE IF NOT EXISTS "migrations" (
      "id" SERIAL NOT NULL, 
      "timestamp" bigint NOT NULL, 
      "name" character varying NOT NULL, 
      CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id")
    );

    -- Insert migration records to mark them as applied
    INSERT INTO "migrations" ("timestamp", "name") 
    VALUES 
      (1736539968508, 'Migrations1736539968508'),
      (1737479055587, 'Migrations1737479055587')
    ON CONFLICT DO NOTHING;
