apiVersion: v1
kind: Secret
metadata:
  name: free-ebay-db-credentials
  namespace: free-ebay
type: Opaque
data:
  # These are base64 encoded values
  DB_USER: c3Ryb2thMDE=  # stroka01
  DB_PASSWORD: YWRtaW4=   # admin
