export const CART_MOCK_SERVICE = Symbol('CART_MOCK_SERVICE');
export const CART_ITEM_MOCK_SERVICE = Symbol('CART_ITEM_MOCK_SERVICE');
export const ORDER_MOCK_SERVICE = Symbol('ORDER_MOCK_SERVICE');
export const ORDER_ITEM_MOCK_SERVICE = Symbol('ORDER_ITEM_MOCK_SERVICE');
export const PAYMENT_MOCK_SERVICE = Symbol('PAYMENT_MOCK_SERVICE');
export const SHIPMENT_MOCK_SERVICE = Symbol('SHIPMENT_MOCK_SERVICE');
