export const CART_REPOSITORY = Symbol('CART_REPOSITORY');
export const CART_ITEM_REPOSITORY = Symbol('CART_ITEM_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const SHIPMENT_REPOSITORY = Symbol('SHIPMENT_REPOSITORY');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
