export const ADD_TO_CART_USE_CASE_TOKEN = Symbol('ADD_TO_CART_USE_CASE_TOKEN');
export const REMOVE_FROM_CART_USE_CASE_TOKEN = Symbol(
  'REMOVE_FROM_CART_USE_CASE_TOKEN',
);
export const RETRIEVE_CART_USE_CASE_TOKEN = Symbol(
  'RETRIEVE_CART_USE_CASE_TOKEN',
);
export const CLEAR_CART_USE_CASE_TOKEN = Symbol('CLEAR_CART_USE_CASE_TOKEN');
export const CREATE_ORDER_USE_CASE_TOKEN = Symbol(
  'CREATE_ORDER_USE_CASE_TOKEN',
);
export const GET_ORDER_DETAIL_USE_CASE_TOKEN = Symbol(
  'GET_ORDER_DETAIL_USE_CASE_TOKEN',
);
export const GET_ALL_USER_ORDERS_USE_CASE_TOKEN = Symbol(
  'GET_ALL_USER_ORDERS_USE_CASE_TOKEN',
);
export const CANCEL_ORDER_USE_CASE_TOKEN = Symbol(
  'CANCEL_ORDER_USE_CASE_TOKEN',
);
export const SHIP_ORDER_USE_CASE_TOKEN = Symbol('SHIP_ORDER_USE_CASE_TOKEN');
export const PROCEED_PAYMENT_USE_CASE_TOKEN = Symbol(
  'PROCEED_PAYMENT_USE_CASE_TOKEN',
);
export const CHECK_PAYMENT_STATUS_USE_CASE_TOKEN = Symbol(
  'CHECK_PAYMENT_STATUS_USE_CASE_TOKEN',
);
export const CREATE_CART_USE_CASE_TOKEN = Symbol('CREATE_CART_USE_CASE_TOKEN');
