export const ADD_TO_CART_USE_CASE = Symbol('ADD_TO_CART_USE_CASE');
export const REMOVE_FROM_CART_USE_CASE = Symbol('REMOVE_FROM_CART_USE_CASE');
export const RETRIEVE_CART_USE_CASE = Symbol('RETRIEVE_CART_USE_CASE');
export const CLEAR_CART_USE_CASE = Symbol('CLEAR_CART_USE_CASE');
export const CREATE_ORDER_USE_CASE = Symbol('CREATE_ORDER_USE_CASE');
export const GET_ORDER_DETAIL_USE_CASE = Symbol('GET_ORDER_DETAIL_USE_CASE');
export const GET_ALL_USER_ORDERS_USE_CASE = Symbol(
  'GET_ALL_USER_ORDERS_USE_CASE',
);
export const CANCEL_ORDER_USE_CASE = Symbol('CANCEL_ORDER_USE_CASE');
export const SHIP_ORDER_USE_CASE = Symbol('SHIP_ORDER_USE_CASE');
export const INITIATE_PAYMENT_USE_CASE = Symbol('INITIATE_PAYMENT_USE_CASE');
export const CHECK_PAYMENT_STATUS_USE_CASE = Symbol(
  'CHECK_PAYMENT_STATUS_USE_CASE',
);
export const CREATE_CART_USE_CASE = Symbol('CREATE_CART_USE_CASE');
