name: Core Pipeline

on:
  push:
    paths:
      - "core/**"
      - ".github/workflows/core-pipeline.yml"
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/core-pipeline.yml"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "core/yarn.lock"

      - name: Install dependencies
        working-directory: ./core
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./core
        run: yarn test

      - name: Build project
        working-directory: ./core
        run: yarn build
